### ISSUE TITLE
Consider deprecating?

### ISSUE THREAD

**Issue by DSchau** [contentful/starter-gatsby-blog#24]
Seems like the functionality has largely been superseded by contentful-userland/gatsby-contentful-starter, which seems to be a drastically improved experience.

**Comment by Khaledgarbaya** [comment]
Hey @DSchau,
Thanks for reaching out. This project was intended mainly for onboarding people and it's integrated with the Contentful Web App.
I will reach out to the team responsible for it and see what we can do to remove the confusion

**Comment by muescha** [comment]
it is still on the onboarding process

**Comment by muescha** [comment]
also on https://app.contentful.com/spaces/xxxx/onboarding/deploy
is linked to an old cli

**Comment by eriktoyra** [comment]
The onboarding is unfortunately flawed in its current state. The project is outdated with an old version of Gatsby and the project won't even run. See issues #33 and #34 for errors that prevent the project from running. 

I had high hopes for Contenful's onboarding as it looked very promising but unfortunately the experience below par. You should really address the fact that an onboarding that won't even work sends people interested in Contenful searching for alternatives.

**Comment by muescha** [comment]
@eriktoyra yes - i agree

**Comment by benjamincox** [comment]
This is three months ago. I'm new to Contentful and simply walking through the steps. I'd assume you'll want to onboard developers smoothly... any fix in sight?

**Comment by arpl** [comment]
Fixed in https://github.com/contentful/starter-gatsby-blog/pull/47

**Comment by shawnhansen** [comment]
Why was this issue closed? This onboarding still fails at the npm run dev step.

**Comment by muescha** [comment]
@shawnhansen if with the new Version with Gatsby 2.0 you still have problems it would be good if you create a new issue with the error messages/problems with the npm run dev
